apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
  - name: goserver-http-service
    port: 80    
    protocol: TCP
    nodePort: 30001 # NodePort range: 30000-32767